version: "3"
services:
  db:
    image: mysql
    networks:
      mynetwork:
        ipv4_address: 172.25.0.10
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: myproject
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserpassword
    volumes:
      - _db:/var/lib/mysql

volumes:
  _db:


networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
